### ISSUE TITLE
Add security contact

### ISSUE THREAD

**Issue by amagnasco** [integration-os/integrationos#8]
Hi @paulkr,

I got the following phishing email (note the domain) and there isn't any contact info on your website or a security policy on GH. Wasn't sure of any other way of forwarding this

![image](https://github.com/integration-os/integrationos/assets/13786028/1f9e6462-d3d4-4b18-842c-ff064208c09b)

Best,
Ale

**Comment by moekatib** [comment]
Hi @amagnasco ,

Thanks for keeping an eye out and bringing this to our attention! The email you got was actually from our team — no need to worry. Sorry for any mix-up.

If anything looks off or you've got more questions, just shout out to us here or through our usual channels.

Cheers,
Moe Katib
Co-founder, IntegrationOS

**Comment by spataroinc** [comment]
Totally get it, @amagnasco. I'll email you that invite now!
